# Generated by Django 3.1.3 on 2020-11-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('entrance', models.IntegerField(max_length=2)),
                ('floor', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Дата заявки')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.address')),
            ],
        ),
    ]
