# Generated by Django 3.1.3 on 2020-11-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20201113_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.CharField(blank=True, max_length=2, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_text',
            field=models.CharField(max_length=300, verbose_name='Заявка'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('city', 'street', 'house', 'entrance', 'floor', 'apartment'), name='unique_address'),
        ),
    ]
