# Generated by Django 3.1.3 on 2020-12-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0015_auto_20201211_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='elevator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims_elevator', to='logger.elevator', verbose_name='Лифт'),
        ),
    ]
