# Generated by Django 3.1.3 on 2020-12-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0016_claim_elevator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.owner', verbose_name='Владелец'),
        ),
    ]
