# Generated by Django 3.1.3 on 2020-12-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0017_auto_20201211_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='fix_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
